name: materials_sandbox_env

channels:
  - conda-forge

dependencies:
  - python=3.6
  - pandas
  - pymatgen
  - matplotlib
  - networkx
  - numpy
  - scikit-learn
  - pip
  - pip:
    - glove_python
    - git+https://github.com/lantunes/GraVe.git
